project_name: legitify

before:
  hooks:
    - go mod verify
    - go mod tidy

builds:
  - id: legitify
    binary: '{{ .ProjectName }}'
    main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - '-s'
      - '-w'
      - '-X=github.com/Legit-Labs/legitify/internal/version.Name={{ .ProjectName }}'
      - '-X=github.com/Legit-Labs/legitify/internal/version.Version={{ .Version }}'
      - '-X=github.com/Legit-Labs/legitify/internal/version.Commit={{ .Commit }}'
      - '-extldflags=-static'
    targets:
      - 'darwin_amd64'
      - 'darwin_arm64'
      - 'linux_amd64'
      - 'linux_arm64'
      - 'windows_amd64'
      - 'windows_arm64'
    hooks:
      post: sh -c "if [ '{{ .Ext }}' = '.exe' ] ; then osslsigncode sign -certs /tmp/legit_signature.crt -key /tmp/legit_signature.key -in {{ .Path }} -out {{ .Path }}_signed ; rm {{ .Path }} ; mv {{ .Path }}_signed {{ .Path }} ; fi"


dockers:
  -
    image_templates:
      - 'ghcr.io/legit-labs/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
      - 'ghcr.io/legit-labs/{{ .ProjectName }}:latest'
    build_flag_templates:
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=Strengthen the security posture of your GitHub organization!'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source=https://github.com/legit-labs/legitify'
      - '--label=org.opencontainers.image.title={{ .ProjectName }}'
      - '--label=org.opencontainers.image.version={{ .Version }}'

archives:
  - builds:
      - legitify
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: 'sha256'

release:
  draft: false

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: legitify
    homepage: "https://github.com/Legit-Labs/legitify"
    tap:
      owner: legit-labs
      name: homebrew-legit-labs
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}""
