name: "Legitify Analyze"
description: "Legitify GitHub Action"
branding:
  color: "purple"
  icon: "target"
inputs:
  github_token:
    description: "GitHub Personal Access Token"
    required: true
  analyze_self_only:
    description: "If this is set, only the repo where this action is called from will be analyzed"
    required: false
    default: "false"
  repositories:
    description: "Strings of owner/repo. If this is set, only selected repositories will be analyzed"
    required: false
  legitify_base_version:
    description: "The base version of legitify to use. Non breaking changes will be auto updated."
    required: false
    default: "0.2"
  scorecard:
    description: 'Whether to run scorecard as part of the analysis (no/yes/verbose default to "no")'
    required: false
    default: "no"
  upload-code-scanning:
    description: 'Whether to upload the results to GitHub Code Scanning'
    required: false
    default: "true"
  compile-legitify:
    description: "Compile legitify from source (use legitify_base_version as ref)"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
          node-version: '16'

    - id: setup-go
      if: ${{ inputs.compile-legitify == 'true' }}
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # ratchet:actions/setup-go@v3
      with:
        go-version: 1.19
    - id: compile-legitify
      if: ${{ inputs.compile-legitify == 'true' }}
      shell: bash
      run: |
        git clone https://github.com/Legit-Labs/legitify.git legitify-build
        cd legitify-build
        go build -o "${GITHUB_ACTION_PATH}/legitify"
    - id: analyze
      shell: bash
      env:
        github_token: ${{ inputs.github_token }}
        analyze_self_only: ${{ inputs.analyze_self_only }}
        repositories: ${{ inputs.repositories }}
        legitify_base_version: ${{ inputs.legitify_base_version }}
        scorecard: ${{ inputs.scorecard }}
        upload-code-scanning: ${{ inputs.upload-code-scanning }}
      run: |
        cd "$GITHUB_ACTION_PATH"
        node index.js
    - id: reports
      shell: bash
      run: |
        cp "$GITHUB_ACTION_PATH"/legitify-output.* . || echo 'no files to copy'
    - name: "Upload SARIF as Code Scanning Results"
      if: ${{ inputs.upload-code-scanning == 'true' }}
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: legitify-output.sarif
        category: "legitify-report"
    - name: "Upload outputs as Workflow Artifacts"
      if: ${{ steps.analyze.outputs.is_private == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: legitify-report
        path: legitify-output.*