name: "Legitify Analyze"
description: "Legitify GitHub Action"
branding:
  color: "purple"
  icon: "target"
inputs:
  github_token:
    description: "GitHub Personal Access Token"
    required: true
  analyze_self_only:
    description: "If this is set, only the repo where this action is called from will be analyzed"
    required: false
    default: "false"
  repositories:
    description: "Strings of owner/repo. If this is set, only selected repositories will be analyzed"
    required: false
  legitify_base_version:
    description: "The base version of legitify to use. Non breaking changes will be auto updated."
    required: false
    default: "0.2"
  scorecard:
    description: 'Whether to run scorecard as part of the analysis (no/yes/verbose default to "no")'
    required: false
    default: "no"
  upload_code_scanning:
    description: 'Whether to upload the results to GitHub Code Scanning'
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
          node-version: '16'
    - uses: actions/checkout@v2
    - shell: bash
      run: node index.js
    - name: "Upload SARIF as Code Scanning Results"
      if: ${{ inputs.upload_code_scanning == true }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: legitify-output.sarif
        category: "legitify-report"
    - name: "Upload outputs as Workflow Artifacts"
      uses: actions/upload-artifact@v3
      with:
        name: legitify-report
        path: legitify-output.*