# This is the default behavior, will analyze the organization from which the action is running from.
name: Legitify Analyze
on:
  workflow_dispatch:
  schedule:
    # Runs "At 11:00 on every day-of-week from Monday through Friday"
    - cron: "0 11 * * 1-5"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Legitify Action
        uses: Legit-Labs/legitify@main
        with:
          github_token: ${{ secrets.PAT_FOR_LEGITIFY }}
