source 'https://rubygems.org'

#gem "github-pages", "~> 231", group: :jekyll_plugins

# Specify your Jekyll version here
gem 'jekyll', '3.9.5'

# If you're using any GitHub Pages-supported plugins, list them here
gem "just-the-docs"
gem "jekyll-remote-theme"
gem "kramdown-parser-gfm"
