name: Build & Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # ratchet:actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Lint
        uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc # ratchet:golangci/golangci-lint-action@v3
        with:
          version: v1.29
          args: --timeout=3m
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
  build_and_test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # ratchet:actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -count=1 -shuffle=on -timeout=10m -race ./...
      - name: Vet
        run: go vet -v ./...
