name: E2E Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
permissions:
  contents: read
env:
  REPORT_FILE_PATH: /tmp/out.json
jobs:
  install_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # ratchet:actions/checkout@v3
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # ratchet:actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run GitHub tests
        run: |
          GITHUB_TOKEN=${{ secrets.E2E_ENV_TOKEN }} go run main.go analyze --output-format json --output-file $REPORT_FILE_PATH
      - name: Run output verification
        run: go test e2e/e2e_test.go --report_path=$REPORT_FILE_PATH

