name: E2E Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
  release:
    types: [ published ]
permissions:
  contents: read
env:
  GITHUB_REPORT_FILE_PATH: /tmp/gh_out.json
  GITLAB_REPORT_FILE_PATH: /tmp/gl_out.json
jobs:
  install_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # ratchet:actions/checkout@v3
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # ratchet:actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run GitHub tests
        run: |
          LEGITIFY_TOKEN=${{ secrets.GITHUB_E2E_ENV_TOKEN }} go run main.go analyze --output-format json --output-file $GITHUB_REPORT_FILE_PATH --scm github
      - name: Run github output verification
        run: go test e2e/e2e_test.go -run TestGitHub --report_path=$GITHUB_REPORT_FILE_PATH
      - name: Run GitLab tests
        run: |
          LEGITIFY_TOKEN=${{ secrets.GITLAB_E2E_ENV_TOKEN }} go run main.go analyze --output-format json --output-file GITLAB_REPORT_FILE_PATH --scm gitlab
      - name: Run gitlab output verification
        run: go test e2e/e2e_test.go -run TestGitLab --report_path=GITLAB_REPORT_FILE_PATH
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@28e8b353eabda5998a2e1203aed33c5999944779
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_HOOKS_LEGITIFY_ALERTS }}
          SLACK_CHANNEL: legitify-e2e
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: E2E Tests failed - ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SLACK_TITLE: "Legitify periodic E2E test failed"


