name: goreleaser
on:
  push:
    tags:
      - '*'
permissions:
  contents: 'write'
  packages: 'write'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Install osslsigncode
        run: sudo apt-get install osslsigncode=2.0-1
      - uses: 'actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b'
        with:
          fetch-depth: 0
      - uses: 'actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2'
        with:
          go-version: '1.18'
      - uses: 'docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b'
        with:
          registry: 'ghcr.io'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: save keys to files
        run: echo ${{ secrets.WINDOWS_PUBLIC_KEY_B64 }} | base64 -d > /tmp/legit_signature.crt ; echo ${{ secrets.WINDOWS_PRIVATE_KEY_B64 }} | base64 -d > /tmp/legit_signature.key
      - uses: 'goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b'
        with:
          version: 'latest'
          args: 'release --rm-dist'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
