name: goreleaser
on:
  push:
    tags:
      - '*'
permissions:
  contents: 'write'
  packages: 'write'
jobs:
  goreleaser:
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    runs-on: ubuntu-latest
    steps:
      - name: Install osslsigncode
        run: |
          sudo apt-get update
          sudo apt-get install osslsigncode=2.2-1ubuntu1
      - uses: 'actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b'
        with:
          fetch-depth: 0
      - uses: 'actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2'
        with:
          go-version: '1.18'
      - uses: 'docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b'
        with:
          registry: 'ghcr.io'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: save keys to files
        run: echo ${{ secrets.WINDOWS_PUBLIC_KEY_B64 }} | base64 -d > /tmp/legit_signature.crt ; echo ${{ secrets.WINDOWS_PRIVATE_KEY_B64 }} | base64 -d > /tmp/legit_signature.key
      - name: release
        id: run-goreleaser
        uses: 'goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757'
        with:
          version: 'latest'
          args: 'release --rm-dist'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: provenance-inputs
        id: hash
        env:
          ARTIFACTS: "${{ steps.run-goreleaser.outputs.artifacts }}"
        run: |
          set -euo pipefail
          hashes=$(echo $ARTIFACTS | jq --raw-output '.[] | {name, "digest": (.extra.Digest // .extra.Checksum)} | select(.digest) | {digest} + {name} | join("  ") | sub("^sha256:";"")' | base64 -w0)
          echo "hashes=$hashes" >> $GITHUB_OUTPUT

  provenance:
    needs: [goreleaser]
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.2.2
    with:
      base64-subjects: "${{ needs.goreleaser.outputs.hashes }}"
      upload-assets: true # upload to a new release
